### ISSUE TITLE
Remove hardcoded strings

### ISSUE THREAD

**Issue by DineshBS44** [ACM-VIT/libground#10]
It is always a good practice to put all the strings displayed in the UI in a single folder called strings.xml and call them into the activities or fragments using a tag with which they are declared.

Steps to follow:

-  Remove the hardcoded strings which is a part of UI from all the folders of the activity or fragment.

- Add all of the strings in strings.xml and provide them with a small and appropriate tag.

- Call the strings into the activities or fragments using the tags provided in the strings.xml appropriately.

- Also, make sure you add your details in the ArrayList of the ContributorsFragment.

Things to keep in mind:

- Tag name should be small, must represent the view or content in the UI and should make sense.

For example: If "Glide" is a header in a part of UI, then "glide" may be one of the appropriate tags. Examples of inappropriate tags are somthing like "name1", "header1", etc.

**Note:**
You have to claim the issue first by commenting below, and then start working on the issue. It is mandatory to fork the repo and then send a Pull request after you are done with the implementation.

**Comment by nbrabant** [comment]
i can check for this ;)

**Comment by DineshBS44** [comment]
@nbrabant, Sure! Go ahead.
