### ISSUE TITLE
Fast Android Networking Library

### ISSUE THREAD

**Issue by DineshBS44** [ACM-VIT/libground#13]
Demonstrate the use of Fast Android Networking library.

Steps to follow:

- Create a new Activity and implement Fast Android Networking library. You are free to be as innovative as possible in that Activity.

- Add the library name to the ArrayList in the LibrariesFragment.

- Create an intent to the activity in the LibrariesAdapter(RecyclerView Adapter)

- Add your Name, Github id and LinkedIn ID to the contributors ArrayList in the ContributorsFragment.

An example has been provided with Glide Library.

**Note:**
You have to claim the issue first by commenting below, and then start working on the issue. It is mandatory to fork the repo and then send a Pull request after you are done with the implementation.

**Comment by alvintan05** [comment]
Can I work on this with the same API endopint in Retrofit ?

**Comment by DhaneshShetty** [comment]
@alvintan05 Go ahead

**Comment by alvintan05** [comment]
Okay, Thank you
