### ISSUE TITLE
Implement biometric authentication with BiometricPrompt

### ISSUE THREAD

**Issue by DhaneshShetty** [ACM-VIT/libground#14]
Demonstrate the use of BiometricPrompt

Steps to follow:

- Create a new Activity and implement BiometricPrompt.
- Add the library name to the ArrayList in the LibrariesFragment.
- Create an intent to the activity in the LibrariesAdapter(RecyclerView Adapter)
- Add your Name, Github id and LinkedIn ID to the contributors ArrayList in the ContributorsFragment.

An example has been provided with Glide Library.

**Note:**
You have to claim the issue first by commenting below, and then start working on the issue. It is mandatory to fork the repo and then send a Pull request after you are done with the implementation.

**Comment by alvintan05** [comment]
Can I take this issue?

**Comment by DineshBS44** [comment]
@alvintan05, you can work on the assigned issue first and send a PR. Then, after it is merged, if you still want to take up this issue, then comment here to get assigned.

**Comment by alvintan05** [comment]
@DineshBS44 Can I take this issue ?

**Comment by DineshBS44** [comment]
Yes @alvintan05, go ahead!
