### ISSUE TITLE
Play media with ExoPlayer

### ISSUE THREAD

**Issue by DhaneshShetty** [ACM-VIT/libground#16]
Demonstrate the use of ExoPlayer.

Steps to follow:

- Create a new Activity and implement Exoplayer.
- Add the library name to the ArrayList in the LibrariesFragment.
- Create an intent to the activity in the LibrariesAdapter(RecyclerView Adapter)
- Add your Name, Github id and LinkedIn ID to the contributors ArrayList in the ContributorsFragment.
 
An example has been provided with Glide Library.

**Note:** You have to claim the issue first by commenting below, and then start working on the issue. It is mandatory to fork the repo and then send a Pull request after you are done with the implementation.

**Comment by alvintan05** [comment]
Can I take this issue ?

**Comment by DhaneshShetty** [comment]
Sure @alvintan05.
