### ISSUE TITLE
Array List data pile up 

### ISSUE THREAD

**Issue by alvintan05** [ACM-VIT/libground#24]
I found bug when I navigate to other fragment and then press back button on device. Arraylist at fragment libraries pile up with previous data. Can I make pr of this ?

![Screenshot_20201021-192723.png](https://user-images.githubusercontent.com/32356015/96719618-d2c3b300-13d3-11eb-8e92-abeb351b338a.png)

**Comment by DineshBS44** [comment]
@alvintan05, go ahead!

**Comment by DhaneshShetty** [comment]
@alvintan05 You can work on this.
