### ISSUE TITLE
Implement Lottie Animation Library

### ISSUE THREAD

**Issue by DhaneshShetty** [ACM-VIT/libground#7]
Demonstrate the use of Lottie animation library.

Steps to follow:
- Create a new Activity and implement Lottie animation.
- Add the library name to the ArrayList in the LibrariesFragment.
- Create an intent to the activity in the LibrariesAdapter(RecyclerView Adapter)
- Add your Name, Github id and LinkedIn ID to the contributors ArrayList in the ContributorsFragment.

An example has been provided with Glide Library.

**Note:**
You have to claim the issue first by commenting below, and then start working on the issue. It is mandatory to fork the repo and then send a Pull request after you are done with the implementation.

**Comment by nabillasab** [comment]
I would like to work on this

**Comment by DhaneshShetty** [comment]
Sure @nabillasab assigning it to you...Happy coding!
